services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Comsave\SalesforceOutboundMessageTowerBundle\Command\OutboundMessageTowerListenerCommand:
    tags: ['console.command']